// Backend message templates, used only to recognize display text.
export const backendMessageTemplates: Record<string, string> = {
  coreStartFailed: "核心服务未运行且启动失败",
  manualGearFailed: "应用手动挡位失败",
  fixedSpeedSmartControl: "自定义转速模式下无法开启智能变频",
  unknownHotkey: "未知快捷键动作",
  debugDisabled: "请先开启调试模式",
  frameIndexRequired: "命令 0x47 需要帧索引",
  checksum: "响应校验和错误",
  importEmpty: "导入字符串不能为空",
  importFormat: "导入字符串格式错误",
  importDecode: "导入字符串解码失败",
  importDecompress: "导入字符串解压失败",
  importRead: "导入数据读取失败",
  importDataFormat: "导入数据格式错误",
  importVersion: "不支持的导入版本",
  curvePoints: "风扇曲线至少需要2个点",
  curveTemperatureOrder: "风扇曲线温度点必须递增",
  curveRpmOrder: "风扇曲线转速点必须从左到右非递减",
  invalidDownloadUrl: "无效的下载地址",
  deviceNotReady: "设备尚未就绪或正在挂起",
  fixedSpeedRejected: "固件拒绝了自定义转速设置",
  fixedSpeedExit: "退出固件实时转速模式失败",
  manualRestore: "恢复手动挡位失败",
  fixedSpeedRange: "自定义转速需在 0..5000 RPM 之间",
  pawnIoExists: "PawnIO 安装器返回 183（已存在），已确认系统中仍有 PawnIO 安装记录。",
  pawnIoUninstallTimeout: "PawnIO 卸载超时",
  pawnIoInstallTimeout: "PawnIO 安装超时",
  configDirectory: "用户配置目录不可用",
  manualSwitchFailed: "切换到手动模式失败: {{detail}}",
  coreNotConnected: "未连接到核心服务: {{detail}}",
  coreRestartFailed: "核心服务连接断开且重新启动失败: {{detail}}",
  downloadHost: "下载地址不在允许的来源内: {{detail}}",
  tempDirectory: "创建临时目录失败: {{detail}}",
  downloadRequest: "构造下载请求失败: {{detail}}",
  downloadFailed: "下载失败: {{detail}}",
  installerFile: "创建安装包文件失败: {{detail}}",
  installerWrite: "写入安装包失败: {{detail}}",
  downloadInterrupted: "下载中断: {{detail}}",
  installerSync: "刷新安装包到磁盘失败: {{detail}}",
  configSave: "保存配置到用户配置目录失败: {{detail}}",
  pawnIoMissing: "未找到 PawnIO 安装包，已尝试路径: {{detail}}",
  pawnIoInstallFailed: "PawnIO 安装失败: {{detail}}",
  pawnIoManualInstall: "PawnIO 安装超时，请稍后检查驱动状态或手动运行 {{path}}",
  pawnIoManualUninstall: "PawnIO 卸载超时，请稍后检查驱动状态或手动运行 {{path}}",
  frameIndexRange: "命令 0x47 的帧索引 {{index}} 超出固件缓冲区上限 {{max}}，固件不做越界检查，发送会破坏其内存",
  gearIndexRange: "命令 0x26 的挡位索引 {{index}} 超出 0..3",
  responseTimeout: "等待命令 {{command}} 响应超时",
  responseParse: "无法解析命令 {{command}} 响应",
  firmwareLength: "固件版本响应不完整，需要 4 字节，收到 {{count}} 字节",
  curveTemperatureRange: "风扇曲线第{{index}}个点温度超出范围(最高{{max}}°C)",
  curveRpmRange: "风扇曲线第{{index}}个点RPM超出范围(0-5000)",
  bridgeStarting: "温度桥接启动中，请稍候",
};
