// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWindowsAutoStart() {
  return window['go']['main']['App']['CheckWindowsAutoStart']();
}

export function ClearCoolingBenefit() {
  return window['go']['main']['App']['ClearCoolingBenefit']();
}

export function ConnectDevice() {
  return window['go']['main']['App']['ConnectDevice']();
}

export function CreateRTSSAnchor() {
  return window['go']['main']['App']['CreateRTSSAnchor']();
}

export function DeleteFanCurveProfile(arg1) {
  return window['go']['main']['App']['DeleteFanCurveProfile'](arg1);
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function DownloadAndInstallUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1, arg2, arg3, arg4);
}

export function ExportCoolingBenefitReport() {
  return window['go']['main']['App']['ExportCoolingBenefitReport']();
}

export function ExportDiagnosticPackage() {
  return window['go']['main']['App']['ExportDiagnosticPackage']();
}

export function ExportFanCurveProfiles() {
  return window['go']['main']['App']['ExportFanCurveProfiles']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStartMethod() {
  return window['go']['main']['App']['GetAutoStartMethod']();
}

export function GetAvailableGears() {
  return window['go']['main']['App']['GetAvailableGears']();
}

export function GetBridgeProgramStatus() {
  return window['go']['main']['App']['GetBridgeProgramStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCoolingBenefit() {
  return window['go']['main']['App']['GetCoolingBenefit']();
}

export function GetCurrentFanData() {
  return window['go']['main']['App']['GetCurrentFanData']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetDeviceDebugFrames() {
  return window['go']['main']['App']['GetDeviceDebugFrames']();
}

export function GetDeviceStatus() {
  return window['go']['main']['App']['GetDeviceStatus']();
}

export function GetFanCurve() {
  return window['go']['main']['App']['GetFanCurve']();
}

export function GetFanCurveProfiles() {
  return window['go']['main']['App']['GetFanCurveProfiles']();
}

export function GetFlydigiCompatStatus() {
  return window['go']['main']['App']['GetFlydigiCompatStatus']();
}

export function GetRTSSLayoutStatus() {
  return window['go']['main']['App']['GetRTSSLayoutStatus']();
}

export function GetSmartLightStatus() {
  return window['go']['main']['App']['GetSmartLightStatus']();
}

export function GetTemperature() {
  return window['go']['main']['App']['GetTemperature']();
}

export function GetTemperatureHistory() {
  return window['go']['main']['App']['GetTemperatureHistory']();
}

export function GetThemeCSS(arg1) {
  return window['go']['main']['App']['GetThemeCSS'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportFanCurveProfiles(arg1) {
  return window['go']['main']['App']['ImportFanCurveProfiles'](arg1);
}

export function InitSystemTray() {
  return window['go']['main']['App']['InitSystemTray']();
}

export function IsAutoStartLaunch() {
  return window['go']['main']['App']['IsAutoStartLaunch']();
}

export function IsRunningAsAdmin() {
  return window['go']['main']['App']['IsRunningAsAdmin']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function ManualSetFanSpeed(arg1) {
  return window['go']['main']['App']['ManualSetFanSpeed'](arg1);
}

export function OnWindowClosing(arg1) {
  return window['go']['main']['App']['OnWindowClosing'](arg1);
}

export function OpenThemesFolder() {
  return window['go']['main']['App']['OpenThemesFolder']();
}

export function PersistWindowState() {
  return window['go']['main']['App']['PersistWindowState']();
}

export function PreviewRTSSPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewRTSSPosition'](arg1, arg2, arg3);
}

export function QuitAll() {
  return window['go']['main']['App']['QuitAll']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshDeviceSettings() {
  return window['go']['main']['App']['RefreshDeviceSettings']();
}

export function ReinitializeDeviceFirmware(arg1) {
  return window['go']['main']['App']['ReinitializeDeviceFirmware'](arg1);
}

export function ReinstallPawnIO() {
  return window['go']['main']['App']['ReinstallPawnIO']();
}

export function ResetLearnedOffsets() {
  return window['go']['main']['App']['ResetLearnedOffsets']();
}

export function RestartPawnIO() {
  return window['go']['main']['App']['RestartPawnIO']();
}

export function RestoreWindowPosition(arg1) {
  return window['go']['main']['App']['RestoreWindowPosition'](arg1);
}

export function SaveCoolingBenefitReport(arg1) {
  return window['go']['main']['App']['SaveCoolingBenefitReport'](arg1);
}

export function SaveFanCurveProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFanCurveProfile'](arg1, arg2, arg3, arg4);
}

export function SendDeviceDebugCommand(arg1, arg2) {
  return window['go']['main']['App']['SendDeviceDebugCommand'](arg1, arg2);
}

export function SetActiveFanCurveProfile(arg1) {
  return window['go']['main']['App']['SetActiveFanCurveProfile'](arg1);
}

export function SetAutoControl(arg1) {
  return window['go']['main']['App']['SetAutoControl'](arg1);
}

export function SetAutoStartWithMethod(arg1, arg2) {
  return window['go']['main']['App']['SetAutoStartWithMethod'](arg1, arg2);
}

export function SetBrightness(arg1) {
  return window['go']['main']['App']['SetBrightness'](arg1);
}

export function SetCustomSpeed(arg1, arg2) {
  return window['go']['main']['App']['SetCustomSpeed'](arg1, arg2);
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetExtendedSensors(arg1) {
  return window['go']['main']['App']['SetExtendedSensors'](arg1);
}

export function SetFanCurve(arg1) {
  return window['go']['main']['App']['SetFanCurve'](arg1);
}

export function SetFlydigiCompat(arg1) {
  return window['go']['main']['App']['SetFlydigiCompat'](arg1);
}

export function SetGearLight(arg1) {
  return window['go']['main']['App']['SetGearLight'](arg1);
}

export function SetLightStrip(arg1) {
  return window['go']['main']['App']['SetLightStrip'](arg1);
}

export function SetManualGear(arg1, arg2) {
  return window['go']['main']['App']['SetManualGear'](arg1, arg2);
}

export function SetPowerOnStart(arg1) {
  return window['go']['main']['App']['SetPowerOnStart'](arg1);
}

export function SetSmartStartStop(arg1) {
  return window['go']['main']['App']['SetSmartStartStop'](arg1);
}

export function SetTemperatureHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetTemperatureHistoryEnabled'](arg1);
}

export function SetTemperatureHistoryRetentionHours(arg1) {
  return window['go']['main']['App']['SetTemperatureHistoryRetentionHours'](arg1);
}

export function SetUILocale(arg1) {
  return window['go']['main']['App']['SetUILocale'](arg1);
}

export function SetWindowsAutoStart(arg1) {
  return window['go']['main']['App']['SetWindowsAutoStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function TestBridgeProgram() {
  return window['go']['main']['App']['TestBridgeProgram']();
}

export function TestTemperatureReading() {
  return window['go']['main']['App']['TestTemperatureReading']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGuiResponseTime() {
  return window['go']['main']['App']['UpdateGuiResponseTime']();
}

export function WindowBlurEnabled() {
  return window['go']['main']['App']['WindowBlurEnabled']();
}
