// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {rtss} from '../models';
import {flydigicompat} from '../models';
import {theme} from '../models';
import {context} from '../models';
import {guiapp} from '../models';
import {ipc} from '../models';

export function CheckWindowsAutoStart():Promise<boolean>;

export function ClearCoolingBenefit():Promise<types.CoolingBenefitPayload>;

export function ConnectDevice():Promise<boolean>;

export function CreateRTSSAnchor():Promise<rtss.LayoutStatus>;

export function DeleteFanCurveProfile(arg1:string):Promise<void>;

export function DisconnectDevice():Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExportCoolingBenefitReport():Promise<string>;

export function ExportDiagnosticPackage():Promise<string>;

export function ExportFanCurveProfiles():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAutoStartMethod():Promise<string>;

export function GetAvailableGears():Promise<Record<string, Array<types.GearCommand>>>;

export function GetBridgeProgramStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<types.AppConfig>;

export function GetCoolingBenefit():Promise<types.CoolingBenefitPayload>;

export function GetCurrentFanData():Promise<types.FanData>;

export function GetDebugInfo():Promise<Record<string, any>>;

export function GetDeviceDebugFrames():Promise<Array<types.DeviceDebugFrame>>;

export function GetDeviceStatus():Promise<Record<string, any>>;

export function GetFanCurve():Promise<Array<types.FanCurvePoint>>;

export function GetFanCurveProfiles():Promise<types.FanCurveProfilesPayload>;

export function GetFlydigiCompatStatus():Promise<flydigicompat.Status>;

export function GetRTSSLayoutStatus():Promise<rtss.LayoutStatus>;

export function GetSmartLightStatus():Promise<types.SmartTempLightStatus>;

export function GetTemperature():Promise<types.TemperatureData>;

export function GetTemperatureHistory():Promise<types.TemperatureHistoryPayload>;

export function GetThemeCSS(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function ImportFanCurveProfiles(arg1:string):Promise<void>;

export function InitSystemTray():Promise<void>;

export function IsAutoStartLaunch():Promise<boolean>;

export function IsRunningAsAdmin():Promise<boolean>;

export function ListThemes():Promise<Array<theme.Meta>>;

export function ManualSetFanSpeed(arg1:number):Promise<boolean>;

export function OnWindowClosing(arg1:context.Context):Promise<boolean>;

export function OpenThemesFolder():Promise<void>;

export function PersistWindowState():Promise<void>;

export function PreviewRTSSPosition(arg1:string,arg2:number,arg3:number):Promise<void>;

export function QuitAll():Promise<void>;

export function QuitApp():Promise<void>;

export function RefreshDeviceSettings():Promise<types.DeviceSettings>;

export function ReinitializeDeviceFirmware(arg1:boolean):Promise<types.DeviceSettings>;

export function ReinstallPawnIO():Promise<Record<string, any>>;

export function ResetLearnedOffsets():Promise<void>;

export function RestartPawnIO():Promise<types.BridgeTemperatureData>;

export function RestoreWindowPosition(arg1:guiapp.WindowState):Promise<void>;

export function SaveCoolingBenefitReport(arg1:ipc.SaveCoolingBenefitReportParams):Promise<types.CoolingBenefitPayload>;

export function SaveFanCurveProfile(arg1:string,arg2:string,arg3:Array<types.FanCurvePoint>,arg4:boolean):Promise<types.FanCurveProfile>;

export function SendDeviceDebugCommand(arg1:string,arg2:number):Promise<types.DeviceDebugCommandResult>;

export function SetActiveFanCurveProfile(arg1:string):Promise<void>;

export function SetAutoControl(arg1:boolean):Promise<void>;

export function SetAutoStartWithMethod(arg1:boolean,arg2:string):Promise<void>;

export function SetBrightness(arg1:number):Promise<boolean>;

export function SetCustomSpeed(arg1:boolean,arg2:number):Promise<void>;

export function SetDebugMode(arg1:boolean):Promise<void>;

export function SetExtendedSensors(arg1:boolean):Promise<boolean>;

export function SetFanCurve(arg1:Array<types.FanCurvePoint>):Promise<void>;

export function SetFlydigiCompat(arg1:boolean):Promise<flydigicompat.Status>;

export function SetGearLight(arg1:boolean):Promise<boolean>;

export function SetLightStrip(arg1:types.LightStripConfig):Promise<void>;

export function SetManualGear(arg1:string,arg2:string):Promise<boolean>;

export function SetPowerOnStart(arg1:boolean):Promise<boolean>;

export function SetSmartStartStop(arg1:string):Promise<boolean>;

export function SetTemperatureHistoryEnabled(arg1:boolean):Promise<void>;

export function SetTemperatureHistoryRetentionHours(arg1:number):Promise<void>;

export function SetUILocale(arg1:string):Promise<void>;

export function SetWindowsAutoStart(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestBridgeProgram():Promise<types.BridgeTemperatureData>;

export function TestTemperatureReading():Promise<types.TemperatureData>;

export function UpdateConfig(arg1:types.AppConfig):Promise<void>;

export function UpdateGuiResponseTime():Promise<void>;

export function WindowBlurEnabled():Promise<boolean>;
